### ISSUE TITLE
SIGBUS in process

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rust-sha1#31]
```
Program received signal SIGBUS, Bus error.
[Switching to Thread 0x7ffff5dff700 (LWP 21209)]
0x0000555556001994 in sha1::Sha1State::process::h8efaab3546634499 (self=0x7ffff5de1660, block=0x7fffd7bd8000)
    at /home/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.6.0/src/lib.rs:384
384	            words[i] = (block[off + 3] as u32) | ((block[off + 2] as u32) << 8) |
(gdb) bt
#0  0x0000555556001994 in sha1::Sha1State::process::h8efaab3546634499 (self=0x7ffff5de1660, block=0x7fffd7bd8000)
    at /home/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.6.0/src/lib.rs:384
#1  0x0000555555fffa9c in sha1::Sha1::update::_$u7b$$u7b$closure$u7d$$u7d$::h940de8e162b382e7 (block=0x7fffd7bd8000)
    at /home/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.6.0/src/lib.rs:144
#2  0x0000555556000b2e in sha1::Blocks::input::ha6929b76b482ae80 (self=0x7ffff5de1674, input=..., f=...)
    at /home/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.6.0/src/lib.rs:233
#3  0x0000555555fffa20 in sha1::Sha1::update::h9323c34326cafd35 (self=0x7ffff5de1658, data=...) at /home/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.6.0/src/lib.rs:142
#4  0x00005555557a8b13 in sentry_cli::utils::fs::get_sha1_checksums::hb59b03b2820eaf9b (data=..., chunk_size=1048576) at src/utils/fs.rs:181
#5  0x000055555570eb4e in sentry_cli::utils::dif_upload::ChunkedDifMatch::from::h303ad78b4ec2ce2f (inner=..., chunk_size=1048576) at src/utils/dif_upload.rs:245
#6  0x00005555556e6787 in sentry_cli::utils::dif_upload::upload_difs_chunked::_$u7b$$u7b$closure$u7d$$u7d$::h1fdbe5db809594d1 (m=...) at src/utils/dif_upload.rs:1053
#7  0x00005555556e3fe2 in sentry_cli::utils::dif_upload::prepare_difs::h2b6af38af722c61a (items=..., func=...) at src/utils/dif_upload.rs:693
#8  0x0000555555719af2 in sentry_cli::utils::dif_upload::upload_difs_chunked::h9b0bbbbbacd19065 (options=0x7ffff5de5f08, chunk_options=0x7ffff5de3bf0) at src/utils/dif_upload.rs:1052
#9  0x000055555571f1ca in sentry_cli::utils::dif_upload::DifUpload::upload::hde0700bb9dc0963e (self=0x7ffff5de5f08) at src/utils/dif_upload.rs:1410
```

**Comment by mitsuhiko** [comment]
This likely is not the fault of this crate.
