### ISSUE TITLE
Arithmetic operation overflowed

### ISSUE THREAD

**Issue by nathansizemore** [mitsuhiko/rust-sha1#8]
```
nathan@jarvis ~/Development/bin/rust-sha1 $ cargo test
   Compiling sha1 v0.0.7 (file:///home/nathan/Development/bin/rust-sha1)
     Running target/sha1-fb8a6fcff36fb154

running 1 test
test test_simple ... FAILED

failures:

---- test_simple stdout ----
        thread 'test_simple' panicked at 'arithmetic operation overflowed', src/lib.rs:92



failures:
    test_simple

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:254
```

**Comment by nathansizemore** [comment]
Looks like this may be a compiler bug [#23084](https://github.com/rust-lang/rust/issues/23084)

**Comment by nathansizemore** [comment]
Cannot confirm if this is due to compiler bug.  Other sha1 implementations are working properly, but not this repository...

**Comment by badboy** [comment]
Hit this today as well with nightly from 2015-03-14.

**Comment by badboy** [comment]
Got it fixed using wrapping operations (just like rust-crypto). It's currently in https://github.com/badboy/rust-sha1/tree/wrapping-add
